version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: build/nginx/Dockerfile-nginx
    volumes:
      - ./symfony/:/var/www/symfony
    ports:
      - 8000:80
    networks:
      - symfony
  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile-php
    environment:
      APP_ENV: dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./symfony/:/var/www/symfony/
    networks:
      - symfony
  mysql:
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: user
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - symfony
networks:
  symfony: